### ISSUE TITLE
Implement another surgery

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.catalogdoctor#7]
The doctor found an unhealthy `rid` which he was not able to perform the surgery:

```
2019-08-27 15:34:15 ERROR Products.ZCatalog A different document with value '2f2ce09131144d66a6985b3b91ebc44e' already exists in the index.'
rid 444042175 ('/some/path'):
- Reindexed UID index and updated metadata.
```

And in the post-surgery health check:

```
Catalog data is unhealthy, found 7 unhealthy rids:

rid 444042175 ('/some/path'):
- in_catalog_not_in_uuid_index
- in_uuid_unindex_not_in_uuid_index

Not all health problems could be fixed, aborting.
```

What does that mean?

**Comment by deiferni** [comment]
@mbaechtold  so, iirc you have found out that in this case content needed to be deleted due to duplicate UIDs in combination with zexport/zimport. This is something the doctor cannot fix and requires manual user action. I'd close the issue. Objections?

**Comment by mbaechtold** [comment]
Yes, you are right!
